cmd: "npm start"
name: "NPM Start"
# args:
#   - <argument1>
#   - <argument2>
# sh: true,
# cwd: <current working directory for `cmd`>
# env:
#   VARIABLE1: "VALUE1"
#   VARIABLE2: "VALUE2"
# errorMatch:
#   - ^regexp1$
#   - ^regexp2$
# warningMatch:
#   - ^regexp1$
#   - ^regexp2$
# keymap: <keymap string>
# atomCommandName: namespace:command
targets:
  #dev: #extraTargetName
      #cmd: "npm run dev"
      # args:
      # (any previous options are viable here except `targets` itself)
  build:
      cmd: 'npm run build'
